### ISSUE TITLE
M117 via MQtt

### ISSUE THREAD

**Issue by FlyingEagle** [jneilliii/OctoPrint-MQTTPublish#1]
hi,

is there a way to send a (= the actual) M117 message via mqtt automatically (not manually via publish and button)?

regards

**Comment by jneilliii** [comment]
No, this plugin does not do that, but wouldn't be too difficult to incorporate that option.

**Comment by FlyingEagle** [comment]
Would be nice ;-)

**Comment by jneilliii** [comment]
I just committed to the dev branch a version that allows for configuring gcode processing.  Currently implemented with the command like `@MQTTPublish topic message`. After thinking about it though, I think I'm going to change the logic up and use a configurable gcode command, defaulting to `@MQTTPublish` to let the user configure.  But as I type this, it may not fit your specific needs.  Are you thinking of implementing this with some form of M117 progress plugin to allow for forwarding those messages to a MQTT broker?  If so, this implementation won't work.

**Comment by jneilliii** [comment]
Just committed another update to the dev branch that enables an M117 option. Configure topic  in settings to publish messages to.

**Comment by FlyingEagle** [comment]
How do i to install this?

**Comment by jneilliii** [comment]
Go into octoprint plugin manager and use the following url to install the dev branch version.  Report back here if it works for you and I can release as a new version to the master branch.

https://github.com/jneilliii/OctoPrint-MQTTPublish/archive/dev.zip

**Comment by jneilliii** [comment]
Went ahead and pushed this to master and made it the newest release version. Feature request implemented with #2.
