### ISSUE TITLE
Not able to utilize FA icons

### ISSUE THREAD

**Issue by dannieboiz** [jneilliii/OctoPrint-MQTTPublish#11]
plugin is working just fine but I'm unable to utilize an of the FA icon sets. Is there a master list of what's usable?

**Comment by jneilliii** [comment]
It should be linked in the settings by clicking the info button next to class.

https://fontawesome.com/v4.7.0/icons/

**Comment by dannieboiz** [comment]
ahh got it now... had to use fa-<name> on some. Seems to be working.
