### ISSUE TITLE
icon name with - in it

### ISSUE THREAD

**Issue by DerDoubleD** [jneilliii/OctoPrint-MQTTPublish#13]
icon names with - in it, does not work.
example: toggle-ondoes not work.
the entry: "icon-toggle-on" or "icon-toggle-off" does not work.
can you fix this please

**Comment by jneilliii** [comment]
Try the fontawesome class name... fa-toggle-on/fa-toggle-off

**Comment by DerDoubleD** [comment]
OK, that works. Thanks!
