### ISSUE TITLE
Inoperable After Upgrade to Octoprint Version 1.5.3

### ISSUE THREAD

**Issue by kasonknight** [jneilliii/OctoPrint-MQTTPublish#14]
First off, thanks for all of the awesome work with all of your plugins!

We've been using the the MQTT plugins for a while now and they have always worked great. Just recently I upgraded octoprint to Version 1.5.3 on a few printers and this plugin seems to have stopped functioning - whenever the button is clicked to send the MQTT message the button icon just spins in circles indefinitely and the message is never sent.

Is it possible something has changed in the latest Octoprint versions that may have caused an issue? We have several V1.4 octoprint instances that are still working fine. The MQTT Plugin itself seems to be functioning normally - we've only noticed an issue with the the MQTT Publish plugin.

Thanks again!

**Comment by jneilliii** [comment]
I'll have to double-check since I haven't used this plugin since I made it, but there shouldn't be any reason for it to not be working. Do you see any errors in your octoprint.log?

**Comment by jneilliii** [comment]
I just double checked by installing the plugin and it seems to be working fine. I press the button and the configured message is sent to the MQTT server.

![image](https://user-images.githubusercontent.com/5249455/110405247-49dda900-804e-11eb-80c7-e63369fafd2c.png)

![image](https://user-images.githubusercontent.com/5249455/110405298-5c57e280-804e-11eb-8474-4683978eb1ac.png)

**Comment by kasonknight** [comment]
Hmm, thanks for checking into this so quickly. We had the same effect of several machines all at the same time after they were upgraded. Do you mind confirming which version octoprint your are running? I can't see why the upgrade would cause it but that's the only common denominator we could find.  I'll do some additional investigating and will report back. Thanks again!

**Comment by jneilliii** [comment]
OctoPrint 1.5.3 Python 3.7.3 OctoPi 0.18.0
