### ISSUE TITLE
small update to readme.md

### ISSUE THREAD

**Issue by planetar** [jneilliii/OctoPrint-MQTTPublish#15]
Under **Action Commands** there is an example how to configure Marlin for it.
Unfortunately, with Marlin changes of the names of constants are frequent and on 2.0.9.1 the item is 
#define CUSTOM_MENU_MAIN

Maybe just a short heads-up could help.

Works like a charm! Thanks for that

**Comment by jneilliii** [comment]
Thanks, apparently this was changed in 2.0.8. I have added a note to the readme.
