### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by 530projects** [jneilliii/OctoPrint-MQTTPublish#5]
How do you get other icons from Font Awesome to work? I can only get "icon-home" to show anything. I use a MQTT relay to turn my printer on and off and I would like to use the "icon-toggle-on" and "icon-toggle-off" for the buttons. I also tried changing the main button on the top to the "icon-broadcast-tower". But all of them do not load and they are just blank once I restart octoprint. 

For reference I also tried "icon-wifi", "icon-ban", "icon-f015", "icon-f519" and just "wifi" and none of them loaded the icon either. The only one that seems to work is "icon-home".

I will poke around to see if I can help fix it, but my coding skills are not as good as yours I am afraid.

**Comment by jneilliii** [comment]
Let me double-check, but I think this plugin only supports the glyphicons available from bootstrap 2.  Just curious, what relay are you using?  You may be more interested in my TasmotaMQTT plugin, if by chance that is what you are using.

**Comment by jneilliii** [comment]
So the link from the header is redirecting to the most recent version of fontawesome, I'll need to fix that.  The bundled version with OctoPrint is an older version 3.2.1.  You should be able to use any of the icon classes from this link.

https://fontawesome.com/v3.2.1/icons/

**Comment by 530projects** [comment]
I followed the link both on this github page and by click the help button in the plugin settings on octoprint.

After digging through the code and following a rabbit trail, I found this webpage instead: [http://khan.github.io/Font-Awesome/icons/](http://khan.github.io/Font-Awesome/icons/)

So far, all of the icons that I have tried on this page have worked. (even without restarting octoprint). The selection is a little smaller, but I ended up using "icon-rss" for the main button on top, and "icon-off" for the power ON and "icon-minus-sign" for power OFF.

**Comment by 530projects** [comment]
This is the MQTT relay that I am using. [https://www.youtube.com/watch?v=E54d9DRWYsM](https://www.youtube.com/watch?v=E54d9DRWYsM)

I have found that Tasmota is unreliable when pushing he button to toggle on/off, so I wrote my own firmware. If interested, you can find more about it on my github page here: [https://github.com/530projects/SonoffLightSwitch_v2](https://github.com/530projects/SonoffLightSwitch_v2)

**Comment by jneilliii** [comment]
Thanks, I'll check it out.  Might write a similar plugin to control it.  Either way, I just pushed an updated 0.5.0 branch and will release it as a version shortly that updates the available fontawesome to 5.0.13.  Then you can use the ones you wanted to. `fa-toggle-on` and `fa-toggle-off`.

![image](https://user-images.githubusercontent.com/5249455/41327307-f75f1564-6e90-11e8-88df-f5562e0ec89d.png)

**Comment by jneilliii** [comment]
I just realized the update wasn't necessary.  If you used `fa fa-toggle-on` on the previous version it would work, so I'm reverting this last update as it conflicts with the built in fontawesome library. I will push an update to account for the base `fa` icon class so you don't have to put that in the settings.
