### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by henrikl2000** [jneilliii/OctoPrint-MQTTPublish#7]
Hi,
When I try to install MQTTPublish I get an errror
Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
Command "python setup.py egg_info" failed with error code 255 in /tmp/pip-N8Zjoi-build/

What can I do to fix this?
Tia

**Comment by jneilliii** [comment]
How are you installing?

**Comment by henrikl2000** [comment]
I am installing from an SSH connection. Using the following pip install "https://github.com/jneilliii/OctoPrint-MQTTPublish/archive/master.zip" from this link https://plugins.octoprint.org/plugins/mqttpublish/

**Comment by jneilliii** [comment]
Gotcha, so using that method you need to run the following.

```
cd ~/oprint/bin
./pip install https://github.com/jneilliii/OctoPrint-MQTTPublish/archive/master.zip
```

Alternatively, just open plugin manager in octoprint, press the get more button, and copy/paste that url in the bottom and press install.

**Comment by henrikl2000** [comment]
Thank you very much for your help. Now I just need to figure out how to connect it to my OpenHAB
