### ISSUE TITLE
@MQTTPublish from printer

### ISSUE THREAD

**Issue by Fernando-Checa** [jneilliii/OctoPrint-MQTTPublish#8]
If I issue:

> @MQTTPublish octo turnoff

from octoprint's terminal, it works as expected, and the message is transmitted.
But If I use something like this from marlin:

`MENU_ITEM(gcode, "TURN OFF ENDER 3", PSTR("@MQTTPublish octo turnoff"));`

it doesn't work. All I get from the terminal is:

> Recv: echo:Unknown command: "@MQTTPublish octo turnoff"

How can I send a command from marlin that actually triggers the action in Octoprint?

**Comment by jneilliii** [comment]
Yeah, the plugin currently only sees the commands that go through the sending queue from octoprint. Similar issue would occur if you put the command in a gcode file and printed it from the sd card, as those commands don't go through the octoprint queue.  I may be able to achieve this in a future update using an echo command maybe.

In the meantime, theoretically you could use the [Action Commands](https://plugins.octoprint.org/plugins/actioncommands/) plugin and update your MENU_ITEM to use an action command, which will then trigger the GCODE command you configure in it's settings maybe.

**Comment by jneilliii** [comment]
The `MQTTPublish` action hook was added in version 0.6.0. You would need to update your MENU_ITEM to use an action command like `M118 //action:MQTTPublish octo turnoff`.
